spring:
    datasource:
        username: postgres
        url: jdbc:postgresql://localhost:5432/user-task
        password: secret
    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true
                trace: false
            path: /h2-console
            allowed-origins: "*"
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    sql:
        init:
            platform: postgres
    data:
        redis:
        database: 0
        host: localhost
        port: 6379
        password:
        timeout: 60000
        mongodb:
            database: example
            uri: mongodb://root:example@localhost:27017/admin?connectTimeoutMS=10000&authSource=admin
feign:
    name: jplaceholder
    base-url: "https://jsonplaceholder.typicode.com"
    photo-resource: "/photos"
server:
    port: 8080
    servlet:
        context-path: /example
        session:
            timeout: 21600s

    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: my-consumer-group
            auto-offset-reset: earliest
            properties:
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            bootstrap-servers: localhost:9092
            properties:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: org.apache.kafka.common.serialization.StringSerializer